name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Remove conflicting versions of solc
      - name: Remove existing solc versions
        run: |
          sudo apt-get remove --purge -y solc || true
          sudo snap remove solc || true
          rm -rf ~/.solc-select || true

      # Update system and install snap
      - name: Update the system and install snapd
        run: |
          sudo apt-get update && sudo apt-get install -y snapd

      # Install solc 0.8.28 using snap
      - name: Install solc using snap
        run: |
          sudo snap install solc --channel=0.8/stable
          solc --version

      # Debug: Verify the solc path
      - name: Debug solc path
        run: which solc

      # Install Slither
      - name: Install Slither
        run: pip install slither-analyzer

      # Debug: Confirm Slither installation
      - name: Debug Slither installation
        run: slither --version

      # Run Slither analysis
      - name: Run Slither Analysis
        run: slither .