name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 1: Remove conflicting versions of solc
    - name: Remove conflicting solc versions
      run: |
        sudo apt-get remove --purge -y solc || true
        rm -rf ~/.solc-select || true
        rm -f /usr/local/bin/solc || true
        rm -f /snap/bin/solc || true

    # Step 2: Install solc-select and configure correct version
    - name: Install solc-select and correct solc version
      run: |
        wget -qO- https://raw.githubusercontent.com/crytic/solc-select/master/install.sh | bash
        solc-select install 0.8.28
        solc-select use 0.8.28

    # Step 3: Verify solc version
    - name: Verify solc version
      run: solc --version

    # Step 4: Install Slither
    - name: Install Slither
      run: pip install slither-analyzer

    # Step 5: Run Slither analysis
    - name: Run Slither Analysis
      env:
        PATH: ~/.solc-select/bin:$PATH
      run: slither .