name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clear Existing Solc
      run: |
        sudo rm -f /usr/local/bin/solc
        sudo apt-get remove -y solc

    - name: Install Solc 0.8.28
      run: |
        wget https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.28 -O /usr/local/bin/solc
        chmod +x /usr/local/bin/solc
        solc --version

    - name: Install Slither
      run: pip install slither-analyzer

    - name: Run Slither
      run: slither .
