name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install correct solc version (0.8.28)
      run: |
        wget https://github.com/ethereum/solidity/releases/download/v0.8.28/solc-static-linux
        chmod +x solc-static-linux
        sudo mv solc-static-linux /usr/bin/solc
        solc --version

    - name: Install Slither
      run: |
        pip install slither-analyzer

    - name: Run Slither
      run: slither .
