name: Security Analysis

on:
  push:
    branches:
      - main
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Solc-Select and Specific Solidity Version
      run: |
        # Update the system and install dependencies
        sudo apt update
        sudo apt install -y curl python3 python3-pip
        # Clone and install solc-select
        git clone https://github.com/crytic/solc-select.git
        cd solc-select
        sudo python3 setup.py install
        cd ..
        # Install and use Solidity version 0.8.28
        solc-select install 0.8.28
        solc-select use 0.8.28
        # Verify the installed version
        solc --version

    - name: Install Slither
      run: |
        # Upgrade pip
        pip install --upgrade pip
        # Install Slither Analyzer
        pip install slither-analyzer

    - name: Run Slither Analysis
      run: |
        # Run Slither on the smart contracts
        slither .