name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Remove any existing solc installations to prevent conflicts
    - name: Remove existing solc installations
      run: |
        sudo apt-get remove --purge -y solc || echo "No existing solc to remove"

    # Step 3: Install solc-select and the required solc version
    - name: Install solc-select and the correct solc version
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install solc-select
        solc-select install 0.8.28
        solc-select use 0.8.28
        solc --version  # Verify the installed version

    # Step 4: Install Slither
    - name: Install Slither
      run: pip install slither-analyzer

    # Step 5: Run Slither for security analysis
    - name: Run Slither
      run: slither .
      