name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Remove any existing solc installations to prevent conflicts
    - name: Remove existing solc installations
      run: |
        sudo apt-get remove --purge -y solc || echo "No existing solc to remove"

    # Step 3: Install solc-select and the required solc version
    - name: Install solc-select and the correct solc version
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install solc-select
        solc-select install 0.8.28
        solc-select use 0.8.28

    # Step 4: Verify and debug solc version installation
    - name: Verify solc version
      run: |
        echo "Checking solc version..."
        solc --version
        which solc
        ls -l $(which solc)
        echo "Environment variables:"
        printenv
        echo "Python version:"
        python3 --version
        echo "Pip version:"
        pip --version
        solc-select versions

    # Step 5: Install Slither
    - name: Install Slither
      run: pip install slither-analyzer

    # Step 6: Run Slither for security analysis
    - name: Run Slither
      run: slither .