name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install solc-select and the correct solc version
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ethereum/ethereum
        sudo apt-get update
        sudo apt-get install -y solc
        wget -qO- https://raw.githubusercontent.com/crytic/solc-select/master/install.sh | bash
        solc-select install 0.8.28
        solc-select use 0.8.28
        echo "Using solc version:"
        solc --version
        echo "PATH=$HOME/.solc-select:$PATH" >> $GITHUB_ENV

    - name: Install Slither
      run: pip install slither-analyzer

    - name: Run Slither
      run: slither .
