name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Use Docker to run the analysis with the correct solc version
    - name: Run Slither in Docker
      run: |
        docker run --rm -v $(pwd):/src -w /src trailofbits/eth-security-toolbox \
          bash -c "
          solc-select install 0.8.28 &&
          solc-select use 0.8.28 &&
          solc --version &&
          pip install slither-analyzer &&
          slither .
          "

    # Debug steps to verify the environment inside Docker (optional)
    - name: Debug Docker Environment
      run: |
        docker run --rm -v $(pwd):/src -w /src trailofbits/eth-security-toolbox \
          bash -c "
          solc --version &&
          which solc &&
          ls -l \$(which solc) &&
          printenv &&
          python3 --version &&
          pip --version
          "
          