name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Remove existing solc versions
      run: |
        sudo apt-get remove --purge -y solc || true
        rm -rf ~/.solc-select || true

    - name: Install specific solc version
      run: |
        sudo snap install solc --classic
        sudo snap refresh solc --channel=0.8/stable
        solc --version

    - name: Validate Compilation
      run: solc --base-path . --include-path node_modules Marketplace.sol

    - name: Install Slither
      run: pip install slither-analyzer

    - name: Run Slither Analysis
      run: slither . --solc-args "--base-path . --include-path node_modules"