name: Security Analysis

on:
  push:
    branches:
      - audit-findings
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install solc
      run: |
        sudo apt update
        sudo apt install -y solc

    - name: Install Slither
      run: pip install slither-analyzer

    - name: Run Slither
      run: slither .
